<h1><b> Machine Learning With Python: Save And Load Trained Model </b></h1>

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [7]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
lreg = linear_model.LinearRegression()
lreg.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
lreg.coef_

array([ 135.78767123])

In [10]:
lreg.intercept_

180616.43835616432

In [12]:
lreg.predict(5000)

array([ 859554.79452055])

<h2><b>Save the Model to a file using Python Pickle</h2></b>

In [13]:
import pickle

In [17]:
with open('model_pickle','wb') as file:
    pickle.dump(lreg, file)

<h2><b> Load the Saved Model</h2></b>

In [20]:
with open('model_pickle','rb') as file:
    mdl = pickle.load(file)

In [21]:
mdl.coef_

array([ 135.78767123])

In [22]:
mdl.intercept_

180616.43835616432

In [23]:
mdl.predict(5000)

array([ 859554.79452055])

<h1><b>Save Trained Model Using joblib</b></h2>

In [24]:
from sklearn.externals import joblib

In [28]:
joblib.dump(lreg, 'model_joblib')

['model_joblib']

<h2><b>Load Saved Model</b></h2>

In [29]:
model = joblib.load('model_joblib')

In [30]:
model.coef_

array([ 135.78767123])

In [31]:
model.intercept_

180616.43835616432

In [32]:
model.predict(5000)

array([ 859554.79452055])